---
- name: Get Device Facts
  hosts: all
  vars:
    kops_version: "1.9.0"
    kops_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-linux-amd64"
    kops_darwin_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-darwin-amd64"
    kubectl_version: "v1.10.1"
    kubectl_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64"
    kubectl_darwin_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/darwin/amd64"
  tasks:
    - name: Download Kubectl binaries
      get_url:
        url: "{{ kubectl_darwin_download_path }}/{{ item }}"
        dest: /usr/local/bin
        owner: root
        group: admin
        mode: 0755
        force: yes
    # TODO Add hash check
      with_items:
        - kubectl
      when: ansible_os_family == 'Darwin'
      become: true

    - name: Download Kubectl binaries
      get_url:
        url: "{{ kubectl_download_path }}/{{ item }}"
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755
        force: yes
    # TODO Add hash check
      with_items:
        - kubectl
      when: ansible_os_family != 'Darwin'
      become: true
  
    - name: Download Kops binaries
      get_url:
        url: "{{ kops_darwin_download_path }}"
        dest: /usr/local/bin/kops
        owner: root
        group: admin
        mode: 0755
        force: yes
    # TODO Add hash check
      when: ansible_os_family == 'Darwin'
      become: true

    - name: Download Kops binaries
      get_url:
        url: "{{ kops_download_path }}"
        dest: /usr/local/bin/kops
        owner: root
        group: root
        mode: 0755
        force: yes
    # TODO Add hash check
      when: ansible_os_family != 'Darwin'
      become: true
