---
- name: Get Device Facts
  hosts: localhost
  vars:
    kops_version: "1.9.0"
    kops_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-linux-amd64"
    kops_darwin_download_path: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-darwin-amd64"
    kubectl_version: "v1.10.1"
    kubectl_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/linux/amd64"
    kubectl_darwin_download_path: "https://storage.googleapis.com/kubernetes-release/release/{{ kubectl_version }}/bin/darwin/amd64"
  tasks:
    - name: Download Kubectl binaries
      get_url:
        url: "{{ kubectl_darwin_download_path }}/{{ item }}"
        dest: /usr/local/bin
        owner: root
        group: admin
        mode: 0755
        force: yes
    # TODO Add hash check
      with_items:
        - kubectl
      when: ansible_os_family == 'Darwin'
      become: true

    - name: Download Kubectl binaries
      get_url:
        url: "{{ kubectl_download_path }}/{{ item }}"
        dest: /usr/local/bin
        owner: root
        group: root
        mode: 0755
        force: yes
    # TODO Add hash check
      with_items:
        - kubectl
      when: ansible_os_family != 'Darwin'
      become: true

    - name: Download Kops binaries
      get_url:
        url: "{{ kops_darwin_download_path }}"
        dest: /usr/local/bin/kops
        owner: root
        group: admin
        mode: 0755
        force: yes
    # TODO Add hash check
      when: ansible_os_family == 'Darwin'
      become: true

    - name: Download Kops binaries
      get_url:
        url: "{{ kops_download_path }}"
        dest: /usr/local/bin/kops
        owner: root
        group: root
        mode: 0755
        force: yes
    # TODO Add hash check
      when: ansible_os_family != 'Darwin'
      become: true

    - name: Adding lines into bashrc file
      lineinfile:
        path: ~/.bashrc
        line: 'NAME=wiprocluster.wipjenkins.uk'

    - name: Adding lines into bashrc file
      lineinfile:
        path: ~/.bashrc
        line: 'ZONES=us-west-2a,us-west-2b,us-west-2c'

    - name: Echo my_env_var
      shell: "echo $NAME"
      environment:
        NAME: wiprocluster.wipjenkins.uk

    - name: Echo my_env_var
      shell: "echo $KOPS_STATE_STORE"
      environment:
        KOPS_STATE_STORE: s3://wipro-wipjenkins.uk-state-store
        
    - name: Echo my_env_var
      shell: "echo $ZONES"
      environment:
        ZONES: us-west-2a,us-west-2b,us-west-2c

    - name: Create cluster
      command: kops create cluster --node-count 3 --zones $ZONES --master-zones $ZONES --dns-zone wipjenkins.uk --node-size m4.large --master-size  m4.large --topology private  --networking weave $${NAME}

    - name: update kubernetes cluster
      command: kops update cluster $NAME --yes

    - name: Validate cluster
      command: kops validate cluster $NAME
